#!/usr/bin/env python3
"""Write DATA_HUB/MAP.md: one line for every live file in the repo, grouped by area.

The line is the file's own description: a Python module's docstring summary, or a Markdown
file's first heading. So the map stays true without anyone maintaining it. Bulk data folders
and the archive get one row each instead of thousands.

    python3 DATA_HUB/tools/build_map.py
"""
from __future__ import annotations

import ast
import pathlib
import subprocess
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parents[2]
COLLAPSE = {
    "Archived_Do_Not_Refference": "Superseded material. **Do not open.** One line per item in its `ARCHIVE_INDEX.md`",
    "data/archive": "Bar archive (JSONL, ET timestamps), append-only. Refreshed by `DATA_HUB/tools/refresh_archive.py`",
    "csv/raw": "Real CME micro bars to 2026-09-22 (UTC timestamps). **Read-only**",
    "DATA_HUB/levels": "Generated level reports (`update_hub.sh` rewrites them)",
    "tests": "pytest suite for `futures_agents/` and the kept workspace engines (run: `python3 -m pytest -q tests`)",
}
AREAS = [
    ("DATA_HUB", "The hub: start here"),
    ("futures_agents", "Core package (data, indicators, strategies, backtest, risk, agents)"),
    ("workspace/paper/CALL", "CALL desk tools (desk paused 2026-09-29)"),
    ("workspace/paper/REPLAY", "REPLAY desk (still running on its own branch)"),
    ("workspace/roundtable", "Research engines kept for re-use (edge programme, backtesters, replay harness)"),
    ("workspace", "Other research libraries kept for re-use"),
    ("", "Top level and misc"),
]


KNOWN = {
    "_manifest.tsv": "KEEP/ARCHIVE decision + one-line summary per path (input to apply_archive.py)",
    "CALL/BASIS": "CALL desk's contract-basis note (MNQ/NQ, MGC/GC price mapping)",
    "CALL/cont1_results.json": "CONT-1 breakout-prohibition test results (worse than placebo 4/4)",
    "CALL/journal.jsonl": "CALL desk journal: every plan and NO-TRADE decision",
    "CALL/pending.jsonl": "CALL desk plans and their status (resolve.py is the only writer of outcomes)",
    "CALL/state.json": "CALL desk account state: equity, drawdown, closed trades",
    "R1/callouts.jsonl": "REPLAY decisions with visible-bar count (audit trail)",
    "R1/journal.jsonl": "REPLAY trade journal",
    "R1/missed.jsonl": "REPLAY counterfactual prices of stand-downs",
    "R1/state.json": "REPLAY harness state. **The replay agent must not read it**",
    "R1/visible.jsonl": "The only bars the replay agent may see",
    "stops_cache.json": "BT3 governor-replay stop cache (regenerable)",
    "EF3/out/": "EF3 MES/MNQ 60m population/stage-1 outputs, input to the unrun placebo stage",
    "__init__.py": "package marker",
    "ui/assets/": "dashboard front-end asset",
    ".gitkeep": "keeps the folder",
    ".gitignore": "git ignore rules (note: data/archive is tracked on purpose)",
    "desk-config.json": "shared risk configuration for the desk console",
    "futures-desk.spec": "PyInstaller spec for the desk executable",
}


def describe(path: pathlib.Path) -> str:
    own = _own_description(path)
    if own:
        return own
    rel = str(path.relative_to(ROOT))
    return next((v for k, v in KNOWN.items() if k in rel), "")


def _own_description(path: pathlib.Path) -> str:
    if path.suffix == ".sh":
        for line in path.read_text().splitlines()[1:]:
            if line.startswith("#"):
                return line.lstrip("# ").strip()
    try:
        text = path.read_text(errors="replace")
    except (OSError, UnicodeDecodeError):
        return ""
    if path.suffix == ".py":
        try:
            doc = ast.get_docstring(ast.parse(text)) or ""
        except SyntaxError:
            doc = ""
        return doc.strip().splitlines()[0] if doc.strip() else ""
    if path.suffix == ".md":
        for line in text.splitlines():
            if line.strip():
                return line.lstrip("#> ").strip()
    return ""


def main() -> None:
    files = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout.split()
    collapsed = defaultdict(int)
    groups = defaultdict(list)
    for f in files:
        key = next((c for c in COLLAPSE if f == c or f.startswith(c + "/")), None)
        if key:
            collapsed[key] += 1
            continue
        area = next(a for a, _ in AREAS if a == "" or f.startswith(a + "/"))
        groups[area].append(f)
    out = ["# Repository map\n",
           "_Generated by `python3 DATA_HUB/tools/build_map.py`. Each line is the file's own docstring or "
           "heading, so fix the file, not this page._\n",
           "## Bulk folders (collapsed)\n", "| folder | files | what it is |", "|---|---|---|"]
    for k, v in COLLAPSE.items():
        out.append(f"| `{k}/` | {collapsed.get(k, 0)} | {v} |")
    for area, title in AREAS:
        if not groups.get(area):
            continue
        out += [f"\n## {title}" + (f" — `{area}/`" if area else ""), "", "| file | what it is |", "|---|---|"]
        for f in sorted(groups[area]):
            d = describe(ROOT / f).replace("|", "/")
            out.append(f"| `{f}` | {d[:160]} |")
    (ROOT / "DATA_HUB" / "MAP.md").write_text("\n".join(out) + "\n")
    print(f"wrote DATA_HUB/MAP.md ({sum(len(v) for v in groups.values())} files listed, "
          f"{sum(collapsed.values())} collapsed)")


if __name__ == "__main__":
    main()
