#!/usr/bin/env python3
"""Which bounce conditions beat random levels CONSISTENTLY across symbols and timeframes?

One symbol/timeframe beating placebo is easily luck. A level type that beats it on most
of 8 symbol x timeframe runs is worth a trader's attention. Reads the JSON written by
bounce_levels.py and writes DATA_HUB/levels/CONSISTENCY.md.

    python3 DATA_HUB/tools/level_consistency.py

Caveat printed in the report: MNQ and MES are one index complex, so their runs are not
independent; the combined z (Stouffer) overstates certainty when they agree.
"""
from __future__ import annotations

import glob
import json
import pathlib
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parents[2]
LEVELS = ROOT / "DATA_HUB" / "levels"

PLAIN = {
    "PDH": "prior day's high", "PDL": "prior day's low", "PDC": "prior day's close",
    "PD_POC": "prior day's busiest price (volume POC)", "PD_VWAP": "prior day's VWAP",
    "P_RTH_H": "prior regular-session high", "P_RTH_L": "prior regular-session low",
    "PWH": "prior week's high", "PWL": "prior week's low", "ONH": "overnight high",
    "ONL": "overnight low", "SWING": "recent 60m swing high/low", "ROUND": "round number",
    "first_touch": "first time the level is tested", "retest(2+)": "level already tested before",
    "confluence>=2": "2+ other levels stacked within 1/4 ATR", "confluence=0": "level on its own",
    "with_trend": "bounce in the direction of the trend", "counter_trend": "bounce against the trend",
    "RTH": "during regular hours 9:30-16:00 ET", "overnight": "outside regular hours",
    "slow_approach": "price drifted into the level", "fast_approach": "price raced into the level",
    "low_vol": "quiet market", "high_vol": "volatile market", "support": "all supports",
    "resistance": "all resistances", "all": "every touch",
}


def plain(bucket: str) -> str:
    head, *side = bucket.split(" ")
    return PLAIN.get(head, head) + (f" as {side[0].lower()}" if side else "")


def vp_section() -> list[str]:
    """LVN continuation-vs-bounce, pooled across symbols per profile range and condition.
    'lean' = LVN (cont - bounce) minus random prices' (cont - bounce) in the same range."""
    res = [json.load(open(f)) for f in sorted(glob.glob(str(LEVELS / "*_volume_profile.json")))]
    if not res:
        return []
    out = ["\n## Volume profile: at a low-volume node (LVN), continuation or bounce?\n",
           "`extra continuation` = how much MORE often price continued through the LVN than it did through random "
           "prices in the same range (positive = LVNs favour continuation, negative = LVNs favour bouncing). "
           "`symbols agreeing` = how many of the symbols point the same way as the average.\n",
           "| profile range | condition at the LVN | touches | extra continuation (avg) | symbols agreeing | per symbol |",
           "|---|---|---|---|---|---|"]
    windows = [w["window"] for w in res[0]["windows"]]
    conds = list(res[0]["windows"][0]["lvn_by_condition"])
    for wi, wname in enumerate(windows):
        for c in ["LVN (all)"] + conds:
            vals = []
            for r in res:
                w = r["windows"][wi]
                row = w["by_kind"]["LVN"] if c == "LVN (all)" else w["lvn_by_condition"][c]
                a, b = row["real"], row["placebo"]
                if a.get("n", 0) >= 10 and b.get("n"):
                    vals.append((r["symbol"], a["n"], (a["cont"] - a["bounce"]) - (b["cont"] - b["bounce"])))
            if not vals:
                continue
            n = sum(v[1] for v in vals)
            avg = sum(v[2] * v[1] for v in vals) / n
            agree = sum((v[2] > 0) == (avg > 0) for v in vals)
            out.append(f"| {wname} | {c} | {n} | {avg*100:+.0f} pts | {agree}/{len(vals)} | "
                       + ", ".join(f"{s} {d*100:+.0f}" for s, _, d in vals) + " |")
    return out


def main() -> None:
    runs = []
    for f in sorted(glob.glob(str(LEVELS / "*_bounce.json"))):
        runs += json.load(open(f))
    out = ["# Bounce levels — what holds up across ALL symbols\n",
           "_Generated by `python3 DATA_HUB/tools/level_consistency.py` from the per-symbol reports._\n",
           "Runs combined: " + ", ".join(f"{r['symbol']} {r['tf']}m" for r in runs) + ".\n",
           "**How to read this.** For each condition, `beats fake` counts in how many symbol/timeframe runs "
           "real levels did better than randomly-shifted fake levels. `combined z` pools them: above about "
           "+2 is a consistent edge over random, below −2 is consistently *worse* than random. MNQ and MES "
           "move together, so treat the combined z as optimistic.\n"]
    for mode in ("touch", "reclaim"):
        agg = defaultdict(list)
        for r in runs:
            m = r["modes"][mode]
            for row in m["by_type"] + m["by_feature"]:
                if row["real"].get("n", 0) >= 10 and row["z"] is not None:
                    agg[row["bucket"]].append((f"{r['symbol']}{r['tf']}", row["z"], row["real"]["expR"],
                                               row["placebo"]["expR"], row["real"]["n"]))
        rows = []
        for k, v in agg.items():
            zs = [x[1] for x in v]
            rows.append(dict(bucket=k, runs=len(v), pos=sum(z > 0 for z in zs), stouffer=sum(zs) / len(zs) ** 0.5,
                             n=sum(x[4] for x in v), real=sum(x[2] * x[4] for x in v) / sum(x[4] for x in v),
                             fake=sum(x[3] * x[4] for x in v) / sum(x[4] for x in v), detail=v))
        rows.sort(key=lambda r: -r["stouffer"])
        title = "Buy/sell AT the level" if mode == "touch" else "Sweep & reclaim (poke through, close back, enter)"
        out.append(f"\n## {title}\n\n| condition | plain English | beats fake | combined z | avg R real | avg R fake | trades |\n|---|---|---|---|---|---|---|")
        for r in rows:
            out.append(f"| {r['bucket']} | {plain(r['bucket'])} | {r['pos']}/{r['runs']} | {r['stouffer']:+.2f} | "
                       f"{r['real']:+.3f} | {r['fake']:+.3f} | {r['n']} |")
    out += vp_section()
    (LEVELS / "CONSISTENCY.md").write_text("\n".join(out) + "\n")
    print(f"wrote {LEVELS / 'CONSISTENCY.md'}")


if __name__ == "__main__":
    main()
