#!/usr/bin/env python3
"""Emit results/TABLES.md straight from the result JSON so no number is retyped into prose."""
import json, math, pathlib, statistics as st

H = pathlib.Path(__file__).resolve().parent
inv = json.load(open(H / "results/inverse.json"))
f234 = json.load(open(H / "results/f234.json"))
SY = ("MES", "MNQ", "MGC", "MCL")
FAM = {"F1": "AVWAP band fade", "F1b": "AVWAP band continuation", "F2": "naked POC",
       "F3": "fib continuation", "F3b": "fib trend-failure", "F4": "merged-TF LVN"}

rows, is_trials = [], 0
for s in SY:
    for f in ("F1", "F1b", "F3b"):
        r = inv[s][f]; is_trials += r["is_trials"]
        rows.append((s, f, r))
    for f in ("F2", "F3", "F4"):
        r = f234[s][f]; is_trials += r["is_trials"]
        rows.append((s, f, r))
oos = [(s, f, r) for s, f, r in rows if r.get("oos")]
bar = math.sqrt(2 * math.log(len(oos)))

o = ["# ANCH1 results — generated by `mktables.py`, do not hand-edit", "",
     f"In-sample variants evaluated (no significance claimed): **{is_trials}**.",
     f"Out-of-sample confirmations, each run once: **{len(oos)}**.",
     f"Luck bar √(2·ln {len(oos)}) = **{bar:.3f}**.", "",
     "## 1. The 24 out-of-sample confirmations",
     "",
     "`t` is on the trade mean. `z shift` is against 200 circular shifts of the entry times "
     "(same sides, same geometry). `dir` and `lvl` are how many of 10 placebo draws the real "
     "rule beat. A pass needs t ≥ bar **and** z shift ≥ bar **and** both OOS halves positive.", "",
     "| symbol | family | variant chosen on IS | n | avg R | t | z shift | dir | lvl | halves | pass |",
     "|---|---|---|---|---|---|---|---|---|---|---|"]
for s, f, r in sorted(oos, key=lambda x: -(x[2]["oos"]["real"].get("t") or -99)):
    q, rl = r["oos"], r["oos"]["real"]
    t_, z = rl.get("t"), q.get("z_shift")
    h1, h2 = rl.get("h1"), rl.get("h2")
    ok = (t_ or -9) >= bar and (z or -9) >= bar and (h1 or -9) > 0 and (h2 or -9) > 0
    o.append(f"| {s} | {f} {FAM[f]} | `{r['pick']['variant']}` | {rl['n']} | {rl['avg_r']:+.4f} "
             f"| {t_:+.3f} | {(z if z is not None else float('nan')):+.2f} | {q['dir_placebo_beaten']}/10 "
             f"| {q.get('lvl_placebo_beaten','—') if q.get('lvl_placebo_beaten') is not None else '—'}"
             f"{'/10' if q.get('lvl_placebo_beaten') is not None else ''} "
             f"| {(h1 or 0):+.2f} / {(h2 or 0):+.2f} | {'**YES**' if ok else 'no'} |")

o += ["", "## 2. Win rate and payoff together (every OOS arm)", "",
      "A high win rate with a payoff under 1 still loses. Both columns, always.", "",
      "| symbol | family | n | win rate | payoff | avg R | exits (stop/target/session/time) |",
      "|---|---|---|---|---|---|---|"]
for s, f, r in sorted(oos, key=lambda x: (x[0], x[1])):
    rl = r["oos"]["real"]
    e = rl.get("exits", {})
    o.append(f"| {s} | {f} | {rl['n']} | {rl['win']:.0%} | "
             f"{(rl['payoff'] if rl['payoff'] is not None else float('nan')):.2f} | {rl['avg_r']:+.4f} | "
             f"{e.get('stop',0)}/{e.get('target',0)}/{e.get('session',0)}/{e.get('time',0)} |")

o += ["", "## 3. What the account could actually fund", "",
      "Risk per trade is capped at $120 while nothing is proven. `refused` is trades the budget "
      "could not size at one contract.", "",
      "| symbol | family | trades | taken | refused | end equity | max drawdown |",
      "|---|---|---|---|---|---|---|"]
for s, f, r in sorted(oos, key=lambda x: (x[0], x[1])):
    a, rl = r["oos"]["account"], r["oos"]["real"]
    o.append(f"| {s} | {f} | {rl['n']} | {a['taken']} | {a['refused']} | "
             f"${a['end_equity']:,.2f} | ${a['max_dd']:,.2f} |")

o += ["", "## 4. Naked POC: the revisit claim, tested", "",
      "The practitioner claim is that ~80% of naked POCs are revisited within 10 sessions. True — "
      "but so is almost any price in the same range, which is what makes it not a POC property.", "",
      "| symbol | naked POCs live per day | real revisit rate | random price in same range | gap |",
      "|---|---|---|---|---|"]
for s in SY:
    rv = f234[s]["F2"]["revisit"]
    o.append(f"| {s} | {f234[s]['F2']['n_npoc_per_day']:.1f} | {rv['real_rate']:.4f} (n={rv['real_n']}) "
             f"| {rv['ctrl_rate']:.4f} (n={rv['ctrl_n']}) | **{100*(rv['real_rate']-rv['ctrl_rate']):+.2f} pp** |")
o += ["", "Pre-registered threshold was +5.00 pp. The largest gap measured is "
      f"{max(100*(f234[s]['F2']['revisit']['real_rate']-f234[s]['F2']['revisit']['ctrl_rate']) for s in SY):+.2f} pp.", ""]

o += ["## 5. Merged timeframes: why F4 is unmeasurable, not null", "",
      "A confluent LVN needs an LVN on ≥2 of the 1-session / 1-week / 1-month / 3-month 60m "
      "profiles within ¼ ATR. That is rare enough that the arm never reaches the 20-trade floor.", "",
      "| symbol | confluent LVNs per day | single-window LVNs per day | IS trades, confluent break |",
      "|---|---|---|---|"]
for s in SY:
    r = f234[s]["F4"]
    cb = next((x for x in r["is_rows"] if x["variant"] == "confluent_break"), {})
    o.append(f"| {s} | {r['levels_per_day']['confluent']:.2f} | {r['levels_per_day']['single']:.2f} "
             f"| {cb.get('n') or 0} |")

o += ["", "## 6. Where the in-sample search found strongly NEGATIVE structure", "",
      "These are losing rules, measured on in-sample only. They are listed because a reliably "
      "losing rule is information: it says the structure is read backwards by most traders.", "",
      "| symbol | family | variant | n | avg R | t |", "|---|---|---|---|---|---|"]
neg = []
for s, f, r in rows:
    for q in r["is_rows"]:
        if q["t"] is not None and q["t"] <= -3.0 and (q["n"] or 0) >= 60:
            neg.append((s, f, q))
for s, f, q in sorted(neg, key=lambda x: x[2]["t"])[:14]:
    o.append(f"| {s} | {f} | `{q['variant']}` | {q['n']} | {q['avg_r']:+.4f} | {q['t']:+.3f} |")

(H / "results" / "TABLES.md").write_text("\n".join(o) + "\n")
print("\n".join(o[:6]))
print(f"\nwrote results/TABLES.md ({len(o)} lines); IS variants {is_trials}; OOS {len(oos)}; bar {bar:.3f}")
