#!/usr/bin/env python3
"""Emit results/TABLES_PERSYM1.md from results/persym1.json. No number is retyped into prose."""
import json, pathlib

H = pathlib.Path(__file__).resolve().parent
d = json.load(open(H / "results/persym1.json"))
BAR = d["bar"]
FLOOR = 2800.0
o = [f"# PERSYM1 results — generated by `mktables_persym.py`, do not hand-edit", "",
     f"15 confirmations, each run once. Luck bar √(2·ln 15) = **{BAR:.3f}**.",
     "Track E is diagnostic and excluded from the count.", ""]

o += ["## A. Exit management at +0.8R (OQ2) — paired on identical trades", "",
      "Entries are unselected (every eligible 60m RTH bar, direction fixed by the prior bar) so the "
      "exit policy is the only thing varying. `be08` moves the stop to the fill once a bar has traded "
      "+0.8R without touching the stop, effective the next bar. `x08` exits fully at +0.8R. "
      "Differences are per-trade and paired, so entry quality cancels exactly.", "",
      "| symbol | entries | n | base avg R | be08 avg R | x08 avg R | paired be08−base | t | trades changed | both halves |",
      "|---|---|---|---|---|---|---|---|---|---|"]
for s, v in d["A"].items():
    for k, r in v.items():
        b, be = r["base"], r["be08"]
        o.append(f"| {s} | {k} | {b['n']} | {b['avg_r']:+.4f} | {be['avg_r']:+.4f} | {r['x08']['avg_r']:+.4f} "
                 f"| **{be['paired_diff']:+.4f}** | {be['paired_t']:+.2f} | {be['pct_improved']:.1%} "
                 f"| {be['diff_h1']:+.4f} / {be['diff_h2']:+.4f} |")
o += ["", "| symbol | entries | paired x08−base | t | base win rate | x08 win rate | base payoff→x08 payoff |",
      "|---|---|---|---|---|---|---|"]
for s, v in d["A"].items():
    for k, r in v.items():
        b, x = r["base"], r["x08"]
        o.append(f"| {s} | {k} | **{x['paired_diff']:+.4f}** | {x['paired_t']:+.2f} | {b['win']:.1%} | "
                 f"{x['win']:.1%} | 1.5R target → 0.8R target |")
o += ["", "### A2. What the exit policy does to the account (one position at a time, $120 risk cap)", "",
      f"The account dies at **${FLOOR:,.0f}** of drawdown. Rows over that are marked.", "",
      "| symbol | entries | policy | trades taken | refused | end equity | max drawdown | past the floor? |",
      "|---|---|---|---|---|---|---|---|"]
for s, v in d["A"].items():
    for k, r in v.items():
        for pol in ("base", "be08", "x08"):
            a = r["account"][pol]
            o.append(f"| {s} | {k} | `{pol}` | {a['taken']} | {a['refused']} | ${a['end_equity']:,.2f} "
                     f"| ${a['max_dd']:,.2f} | {'**DEAD**' if a['max_dd'] > FLOOR else 'survives'} |")

o += ["", "## B. MES / MNQ daily, 7.4 roll-clean years (OQ6)", "",
      "Stop 1 ATR14, target 2R, 10-bar time exit. Span 2019-05-03 → 2026-09-29, 1,865 bars.", "",
      "| symbol | rule | IS n | IS avg R | OOS n | OOS avg R | t | win | payoff | halves | beat coin flip | shift z | funded |",
      "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
for s, v in d["B"].items():
    for name, r in v.items():
        i_, q, a = r["is"], r["oos"], r["account"]
        o.append(f"| {s} | `{name}` | {i_['n']} | {i_['avg_r']:+.4f} | {q['n']} | {q['avg_r']:+.4f} "
                 f"| {q['t']:+.3f} | {q['win']:.1%} | {q['payoff']:.2f} | {q['h1']:+.3f} / {q['h2']:+.3f} "
                 f"| {r['dir_placebo_beaten']}/10 | {r['z_shift']:+.2f} | **{a['taken']} of {q['n']}** |")

o += ["", "## C. MCL momentum, 240m and 60m (OQ5 retest)", "",
      "The parked claim was *97% of observations positive, t 2.97*. Rule: close beyond the prior "
      "3-bar range in the direction of the 10-bar net move; stop 1 ATR, target 1.5R.", "",
      "| timeframe | IS n | IS avg R | IS t | OOS n | OOS avg R | OOS t | win | payoff | halves | shift z | funded |",
      "|---|---|---|---|---|---|---|---|---|---|---|---|"]
for tf, r in d["C"].items():
    i_, q, a = r["is"], r["oos"], r["account"]
    o.append(f"| {tf} | {i_['n']} | {i_['avg_r']:+.4f} | {i_['t']:+.3f} | {q['n']} | {q['avg_r']:+.4f} "
             f"| {q['t']:+.3f} | {q['win']:.1%} | {q['payoff']:.2f} | {q['h1']:+.3f} / {q['h2']:+.3f} "
             f"| {r['z_shift']:+.2f} | {a['taken']} of {q['n']} |")

r = d["D"]; i_, q = r["is"], r["real"]
o += ["", "## D. MGC value-area edge → prior POC, 60m (OQ3, moved from 30m)", "",
      "| measure | value |", "|---|---|",
      f"| in-sample | n={i_['n']}, {i_['avg_r']:+.4f}R, t {i_['t']:+.3f} |",
      f"| out-of-sample | n={q['n']}, {q['avg_r']:+.4f}R, t {q['t']:+.3f} |",
      f"| win rate / payoff | **{q['win']:.1%} / {q['payoff']:.2f}** |",
      f"| OOS halves | {q['h1']:+.3f} / {q['h2']:+.3f} |",
      f"| direction placebo | avg {r['dir_placebo_avg']:+.4f}, real beat it **{r['dir_placebo_beaten']}/10** |",
      f"| level placebo | avg {r['lvl_placebo_avg']:+.4f}, real beat it {r['lvl_placebo_beaten']}/10 |",
      f"| shift-null z | {r['z_shift']:+.2f} |",
      f"| account | {r['account']['taken']} of {q['n']} funded, end ${r['account']['end_equity']:,.2f}, max dd ${r['account']['max_dd']:,.2f} |"]

o += ["", "## E. MGC fib trend-failure — resting limit vs market order (DIAGNOSTIC)", "",
      "**The expectancy columns are in-sample-contaminated** — this rule was selected using these "
      "same out-of-sample bars, so only the risk and funding columns are evidence here.", "",
      "| entry | trades | median stop (pts) | median stop ($) | vs $120 cap | funded | refused | end equity | avg R (contaminated) |",
      "|---|---|---|---|---|---|---|---|---|"]
for k in sorted(d["E"]):
    r = d["E"][k]; a = r["account"]
    rp, ru = r["median_risk_pts"] or 0, r["median_risk_usd"] or 0
    o.append(f"| `{k}` | {r['n']} | {rp:.2f} | ${ru:,.0f} | {'**under**' if ru <= 120 else 'over'} "
             f"| {a['taken']} | {a['refused']} | ${a['end_equity']:,.2f} | {r['avg_r']:+.4f} |")
o += ["", "The 2-bar and 4-bar limit windows differ by exactly one trade (bar 11306 fills only at the "
      "wider window and then blocks bar 11309 under one-position-at-a-time); every shared trade is "
      "identical, and nothing fills beyond 4 bars. So the gap between those rows is one trade in 26, "
      "not a window effect.", ""]

o += ["## F. The binding constraint across every track: the risk cap, not the edge", "",
      "| study | trades the rule generated | trades the $120 budget could size |", "|---|---|---|"]
tot_t = tot_f = 0
for s, v in d["B"].items():
    for name, r in v.items():
        o.append(f"| {s} daily `{name}` | {r['oos']['n']} | **{r['account']['taken']}** |")
        tot_t += r["oos"]["n"]; tot_f += r["account"]["taken"]
for tf, r in d["C"].items():
    o.append(f"| MCL momentum {tf} | {r['oos']['n']} | {r['account']['taken']} |")
o.append(f"| MGC value-area edge | {d['D']['real']['n']} | {d['D']['account']['taken']} |")
o.append(f"| MGC fib, market entry | {d['E']['golden_market']['n']} | {d['E']['golden_market']['account']['taken']} |")
o.append(f"| MGC fib, resting limit | {d['E']['golden_limit2']['n']} | {d['E']['golden_limit2']['account']['taken']} |")
o += ["", f"Daily index trend-following totals **{tot_f} of {tot_t}** trades fundable.", ""]

(H / "results" / "TABLES_PERSYM1.md").write_text("\n".join(o) + "\n")
print(f"wrote results/TABLES_PERSYM1.md ({len(o)} lines)")
