#!/usr/bin/env python3
"""Build FINDINGS_INDEX.md from NOTES.md — a thematic index of every N-note.

NOTES.md is 638 KB and 260 notes deep. Nobody, including me, can hold that in
mind, and an unindexed log of findings is indistinguishable from no log: the
30430.00 miss (N234) happened while the range endpoints that would have flagged
it were printed in fourteen consecutive reports. This file exists so a finding
can be FOUND.

Owned by agent CALL. Rebuild with: python3 index_notes.py
"""
from __future__ import annotations
import pathlib, re, collections

HERE = pathlib.Path(__file__).resolve().parent

# Themes are matched in order; first hit wins, so put the specific before the general.
THEMES = [
    ("Tool disagrees with its own authority",
     r"disagree|reimplement|local calc|delegat|thresholds?|watch\.py|contradict|authority"),
    ("Gate composition and persistence",
     r"unanimous|persistence|held \d|invocation|tally|first[- ]bar|gate|reversal\(\)"),
    ("Counter-trend detector (reversal_setup)",
     r"reversal_setup|sigma|extension|reclaim|counter[- ]trend|QUALIFIES|climax"),
    ("Entry construction and anchor decay",
     r"EMA|anchor|limit|pullback|offset|decay|N233|migrat"),
    ("Exits, MFE, HEAT and partials",
     r"MFE|HEAT|MAE|partial|0\.8R|exit|target|stop distance"),
    ("Sizing, capacity and the cap",
     r"capacity|cap\b|rule 4|floor|afford|\$2/pt|permitted|sizing|contract"),
    ("Data integrity, feed and staleness",
     r"revis|stale|blind|lag|fetch|vendor|truncat|provisional|new=0|snapshot"),
    ("Resolver and the record",
     r"resolve\.py|outcome|ambiguous|journal|PREREG|ledger|equity|drawdown"),
    ("Session, hours and volatility vetoes",
     r"RTH|pit|session|ATR|stand[- ]down|N214|overnight|liquidity|volume"),
    ("Structure, levels and ranges",
     r"swing|pivot|structure|range|location|fib|shelf|endpoint|N46"),
    ("Scheduling, crons and the harness",
     r"cron|UTC|schedule|EST|EDT|worker|container|CronList"),
    ("Process, discipline and self-correction",
     r"N8|retroactiv|pre-?commit|goalpost|preference|discipline|correct"),
]

def main() -> int:
    text = (HERE / "NOTES.md").read_text(errors="replace")
    # A note heading is any markdown heading whose first token is N<number>.
    pat = re.compile(r"^(#{1,6})\s*(N(\d+))\s*[—\-–:]?\s*(.*)$", re.M)
    notes: dict[int, tuple[str, str]] = {}
    order: list[int] = []
    for m in pat.finditer(text):
        num, title = int(m.group(3)), m.group(4).strip()
        # Addenda repeat a number; keep the FIRST title and append a marker.
        if num in notes:
            head, t = notes[num]
            if "addendum" not in t:
                notes[num] = (head, t + "  *(+addenda)*")
            continue
        notes[num] = (m.group(1), title)
        order.append(num)

    buckets: dict[str, list[int]] = collections.OrderedDict((n, []) for n, _ in THEMES)
    buckets["Unclassified"] = []
    for num in sorted(notes):
        title = notes[num][1]
        for name, rx in THEMES:
            if re.search(rx, title, re.I):
                buckets[name].append(num)
                break
        else:
            buckets["Unclassified"].append(num)

    out = [
        "# FINDINGS INDEX — every N-note in `NOTES.md`, by theme",
        "",
        "**Generated by `index_notes.py`. Do not hand-edit; rebuild it.**",
        "",
        f"`NOTES.md` holds **{len(notes)} findings** across "
        f"{len((HERE / 'NOTES.md').read_text(errors='replace').splitlines()):,} lines. "
        "An unindexed findings log is indistinguishable from no findings log — N234 happened "
        "while the very numbers that would have flagged it were being printed every two minutes. "
        "A note is classified by the first theme its title matches, so a note spanning two themes "
        "appears once, under the earlier one.",
        "",
        "| theme | count | notes |",
        "|---|---|---|",
    ]
    for name in buckets:
        nums = buckets[name]
        if not nums:
            continue
        out.append(f"| {name} | {len(nums)} | "
                   + ", ".join(f"N{n}" for n in nums) + " |")
    out.append("")
    out.append("## Every note, in order")
    out.append("")
    for num in sorted(notes):
        out.append(f"- **N{num}** — {notes[num][1]}")
    out.append("")
    (HERE / "FINDINGS_INDEX.md").write_text("\n".join(out) + "\n")
    print(f"FINDINGS_INDEX.md written: {len(notes)} notes, "
          f"{sum(1 for k in buckets if buckets[k])} themes")
    for name in buckets:
        if buckets[name]:
            print(f"  {len(buckets[name]):>3}  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
